# Azimuth angle in degrees (0-360)
azimuth: 330

# Elevation angle in degrees (-90 to 90)
elevation: 0

# Maximum rotation speed in degrees per frame (0-10)
# The rotation will ease in and out, reaching this speed at the midpoint
speed: 3.5

# Pause duration in seconds after each 360 degree rotation
pause: 0.45

# Continuous mode - when true, rotation continues smoothly without pauses
# The easing function creates natural speed variations at rotation boundaries
continuous: false

# Number of full rotations before pausing (1 = 360°, 2 = 720°, etc.)
rotations: 1

# Easing function for rotation animation
# Available options: linear, quadIn, quadOut, quadInOut, cubicIn, cubicOut, 
# cubicInOut, quartIn, quartOut, quartInOut, quintIn, quintOut, quintInOut,
# sineIn, sineOut, sineInOut, expoIn, expoOut, expoInOut, circIn, circOut,
# circInOut, backIn, backOut, backInOut, elasticIn, elasticOut, elasticInOut,
# bounceIn, bounceOut, bounceInOut
# See: https://github.com/semitable/easing-functions for visualizations
easing: sineInOut

# Frame rate for capturing animation frames as JSON files
# These JSON files can be converted to SVG after animation completes
# Set to 0 to disable frame capture
# Common values: 24, 30, 60 fps
capture_fps: 30

# Height in pixels for rasterized PNG images
# Width will be calculated proportionally based on viewport aspect ratio
raster_height: 100

# Style variations for output
styles:
  - name: "default"
    # Thickness of edge lines in pixels
    stroke_width: 12
    
    # SVG background color
    background: "white"
    
    # Color of the filled dodecahedron shape
    fill: "black"
    
    # Color of the edge lines
    stroke: "white"
    
    # Line end style: round, butt, or square
    stroke_linecap: "round"
    
    # Line corner style: round, bevel, or miter
    stroke_linejoin: "round"
  
  - name: "blueprint"
    stroke_width: 8
    background: "#0A2239"
    fill: "#1E5F8E"
    stroke: "#5EB3FD"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "sunset"
    stroke_width: 10
    background: "#FFF5E1"
    fill: "#FF6B6B"
    stroke: "#FFE66D"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "mono"
    stroke_width: 10
    background: "#FFFFFF"
    fill: "#1A1A1A"
    stroke: "#FFFFFF"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "mono-dark"
    stroke_width: 10
    background: "#0D0D0D"
    fill: "#E5E5E5"
    stroke: "#0D0D0D"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "mono-gray"
    stroke_width: 10
    background: "#F5F5F5"
    fill: "#404040"
    stroke: "#F5F5F5"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "mono-gray-dark"
    stroke_width: 10
    background: "#2A2A2A"
    fill: "#B8B8B8"
    stroke: "#2A2A2A"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "forest"
    stroke_width: 10
    background: "#F5F5DC"
    fill: "#2D4A2B"
    stroke: "#F5F5DC"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "forest-dark"
    stroke_width: 10
    background: "#1A1F1A"
    fill: "#8FBC8F"
    stroke: "#1A1F1A"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "ocean"
    stroke_width: 10
    background: "#F0F8FF"
    fill: "#1E3A5F"
    stroke: "#F0F8FF"
    stroke_linecap: "round"
    stroke_linejoin: "round"
  
  - name: "ocean-dark"
    stroke_width: 10
    background: "#0C1821"
    fill: "#5F9EA0"
    stroke: "#0C1821"
    stroke_linecap: "round"
    stroke_linejoin: "round"
