# Azimuth angle in degrees (0-360)
azimuth: 330

# Elevation angle in degrees (-90 to 90)
elevation: 0

# Maximum rotation speed in degrees per frame (0-10)
# The rotation will ease in and out, reaching this speed at the midpoint
speed: 3.5

# Pause duration in seconds after each 360 degree rotation
pause: 0.45

# Continuous mode - when true, rotation continues smoothly without pauses
# The easing function creates natural speed variations at rotation boundaries
continuous: false

# Number of full rotations before pausing (1 = 360°, 2 = 720°, etc.)
rotations: 1

# Easing function for rotation animation
# Available options: linear, quadIn, quadOut, quadInOut, cubicIn, cubicOut, 
# cubicInOut, quartIn, quartOut, quartInOut, quintIn, quintOut, quintInOut,
# sineIn, sineOut, sineInOut, expoIn, expoOut, expoInOut, circIn, circOut,
# circInOut, backIn, backOut, backInOut, elasticIn, elasticOut, elasticInOut,
# bounceIn, bounceOut, bounceInOut
# See: https://github.com/semitable/easing-functions for visualizations
easing: sineInOut

# Frame rate for capturing animation frames as JSON files
# These JSON files can be converted to SVG after animation completes
# Set to 0 to disable frame capture
# Common values: 24, 30, 60 fps
capture_fps: 30

# Height in pixels for rasterized PNG images
# Width will be calculated proportionally based on viewport aspect ratio
raster_height: 100

# Common stroke settings for all themes
stroke_width: 12
stroke_linecap: "round"
stroke_linejoin: "round"

# Themes to use from themes.json
themes:
  - "mono-light"
  - "mono-dark"
  - "modern-minimal-light"
  - "modern-minimal-dark"
  - "twitter-light"
  - "twitter-dark"
  - "catppuccin-light"
  - "catppuccin-dark"
  - "graphite-light"
  - "graphite-dark"
  - "nature-light"
  - "nature-dark"
  - "supabase-light"
  - "supabase-dark"
  - "neo-brutalism-light"
  - "neo-brutalism-dark"
  - "cosmic-night-light"
  - "cosmic-night-dark"
  - "quantum-rose-light"
  - "quantum-rose-dark"
