# Azimuth angle in degrees (0-360)
azimuth: 330

# Elevation angle in degrees (-90 to 90)
elevation: 0

# Maximum rotation speed in degrees per frame (0-10)
# The rotation will ease in and out, reaching this speed at the midpoint
speed: 5.7

# Pause duration in seconds after each 360 degree rotation
pause: 0.1

# Continuous mode - when true, rotation continues smoothly without pauses
# The easing function creates natural speed variations at rotation boundaries
continuous: false

# Number of full rotations before pausing (1 = 360°, 2 = 720°, etc.)
rotations: 2

# Easing function for rotation animation
# Available options: linear, quadIn, quadOut, quadInOut, cubicIn, cubicOut, 
# cubicInOut, quartIn, quartOut, quartInOut, quintIn, quintOut, quintInOut,
# sineIn, sineOut, sineInOut, expoIn, expoOut, expoInOut, circIn, circOut,
# circInOut, backIn, backOut, backInOut, elasticIn, elasticOut, elasticInOut,
# bounceIn, bounceOut, bounceInOut
# See: https://github.com/semitable/easing-functions for visualizations
easing: quadInOut

# Frame rate for capturing animation frames as JSON files
# These JSON files can be converted to SVG after animation completes
# Set to 0 to disable frame capture
# Common values: 24, 30, 60 fps
capture_fps: 30
