[project]
name = "dodecahedron-creator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.0",
    "svgwrite>=1.4.3",
    "vedo>=2025.5.4",
    "pyyaml>=6.0.2",
    "easing-functions>=1.0.4",
]
